#! /bin/bash

set -e

C=`pwd`

cd gmp
./configure --prefix=$C/usr
make
make install
cd ..

cd mpfr
./configure --prefix=$C/usr --with-gmp=$C/usr
make
make install
cd ..

cd mpc
./configure --prefix=$C/usr --with-gmp=$C/usr --with-mpfr=$C/usr
make
make install
cd ..

mkdir gcc-build
cd gcc-build
../gcc/configure --prefix=$C/gcc-trunk \
    --enable-languages=c,fortran \
    --with-gmp=$C/usr \
    --with-mpfr=$C/usr \
    --with-mpc=$C/usr
make
make install
