#! /bin/bash

set -e

curl -O ftp://ftp.gnu.org/gnu/gcc/gcc-4.7.1/gcc-4.7.1.tar.bz2
curl -O ftp://ftp.gnu.org/gnu/gmp/gmp-5.0.5.tar.bz2
curl -O http://www.mpfr.org/mpfr-current/mpfr-3.1.1.tar.bz2
curl -O http://www.multiprecision.org/mpc/download/mpc-1.0.tar.gz
