#! /bin/bash

set -e

tar xjf gcc-4.7.1.tar.bz2
tar xjf gmp-5.0.5.tar.bz2
tar xjf mpfr-3.1.1.tar.bz2
tar xzf mpc-1.0.tar.gz

mv gmp-5.0.5  gcc-4.7.1/gmp
mv mpfr-3.1.1 gcc-4.7.1/mpfr
mv mpc-1.0    gcc-4.7.1/mpc
